<h1>Connexion</h1>
<div class="form-login">
    <form method="post" action="<?= url('/users/auth') ?>">
        <div class="form-group">
            <label for="user_email">Nom d'utilisateur</label>
            <input type="text" class="form-control <?php if (flash()->has('user_email')) : ?>is-invalid<?php endif ?>" id="user_email" name="user_email">
            <?php if (flash()->has('user_email')) : ?>
                <div class="invalid-feedback"><?= flash()->get('user_email') ?></div>
            <?php endif ?>
        </div>
        <div class="form-group">
            <label for="user_password">Mot de passe</label>
            <input type="password" class="form-control" id="user_password" name="user_password" placeholder="Au moins 6 caractères">
        </div>
        <div class="mt-3">
            <button class="btn btn-primary">Se connecter</button>
        </div>
    </form>
</div>