<h1>Connexion</h1>

<form method="post" action="<?= url('/users/auth') ?>">
    <div class="form-group">
        <label for="user_name">Nom d'utilisateur</label>
        <input type="text" class="form-control <?php if (flash()->has('user_name')): ?>is-invalid<?php endif ?>" id="user_name" name="user_name">
        <?php if (flash()->has('user_name')): ?>
            <div class="invalid-feedback"><?= flash()->get('user_name') ?></div>
        <?php endif ?>
    </div>
    <div class="form-group">
        <label for="user_password">Mot de passe</label>
        <input type="user_password" class="form-control" id="user_password" name="user_password" placeholder="Au moins 6 caractères">
    </div>
    <div class="mt-3">
        <button class="btn btn-primary">Se connecter</button>
    </div>
</form>