<h1>Connexion</h1>

<form method="post" action="<?= url('/users/auth') ?>">
    <div class="form-group">
        <label for="username">Nom utilisateur</label>
        <input type="text" class="form-control <?php if (flash()->has('username')): ?>is-invalid<?php endif ?>" id="username" name="username">
        <?php if (flash()->has('username')): ?>
            <div class="invalid-feedback"><?= flash()->get('username') ?></div>
        <?php endif ?>
    </div>
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Au-moins 6 caractères">
    </div>
    <div class="mt-3">
        <button class="btn btn-primary">Se connecter</button>
    </div>
</form>