<h1>Bienvenue dans votre compte personnel</h1>

<section class="my-account">
    <div class="no-post-reserved">
        <p>Vous n'avez réservé aucune annonce</p>
    </div>
    <div class="post-reserved">
        <p>Vous avez reservé l(es)'annonce(s) suivante(s) : 
            <?php ?>
    </p>
    </div>
    <div class="no-training-reserved">
        <p>Vous n'êtes inscrit à aucune formation</p>
    </div>
    <div class="training-reserved">
        <p>Vous êtes inscrit à la (aux) formation(s) suivante(s) : 
            
        </p>
    </div>
</section>