<h1>Inscription</h1>

<form method="post" action="<?= url('/users/store') ?>">
    <div class="form-group">
        <label for="username">Nom utilisateur</label>
        <input type="text" class="form-control <?php if (flash()->has('username')): ?>is-invalid<?php endif ?>" id="username" name="username">
        <?php if (flash()->has('username')): ?>
            <div class="invalid-feedback"><?= flash()->get('username') ?></div>
        <?php endif ?>
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email">
    </div>
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input type="password" class="form-control <?php if (flash()->has('password')): ?>is-invalid<?php endif ?>" id="password" name="password" placeholder="Au-moins 6 caractères">
        <?php if (flash()->has('password')): ?>
            <div class="invalid-feedback"><?= flash()->get('password') ?></div>
        <?php endif ?>
    </div>
    <div class="mt-3">
        <button class="btn btn-primary">S'inscrire</button>
    </div>
</form>