<h1>Inscription</h1>

<div class="form-register">
    <form method="post" action="<?= url('/users/store') ?>" class="form-register">
        <div class="form-group">
            <label for="user_name">Nom et Prénom</label>
            <input type="text" id="user_name" name="user_name" required>
        </div>
        <div class="form-group">
            <label for="user_email">Email</label>
            <input type="text" id="user_email" name="user_email" required>
        </div>
        <div class="form-group">
            <label for="user_address">Adresse</label>
            <input type="text" id="user_address" name="user_address" required>
        </div>
        <div class="form-group">
            <label for="user_income">Revenu Fiscal de Référence</label>
            <input type="number" id="user_income" name="user_income" required>
        </div>
        <div class="form-group">
            <label for="user_password">Mot de passe</label>
            <input type="password" id="user_password" name="user_password" placeholder="Au moins 6 caractères" required>
        </div>
        <div class="mt-3">
            <button class="btn btn-primary">S'inscrire</button>
        </div>
    </form>
</div>