<h1>Créer une session de formation</h1>

<form action="<?= url('/trainings/store') ?>" method="post">
    <div class="form-group">
        <label for="training_title">Titre</label>
        <input type="text" class="form-control" name="training_title" id="training_title">
    </div>
    <div class="form-group">
        <label for="training_content">Description</label>
        <textarea name="training_content" id="training_content" cols="30" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="training_startdate">Date de début</label>
        <input type="datetime-local" class="form-control" name="training_startdate" id="training_startdate">
    </div>
    <div class="mt-3">
        <button class="btn btn-primary">Ajouter</button>
    </div>
</form>