<h1>Liste des sessions de formation</h1>

<div class="items-table">
    <?php foreach ($trainings as $training) : ?>
        <div class="square">
            <header>
                <h2><?= $training['training_title'] ?></h2>
            </header>
            <?= $training['training_content'] ?>
            <?php if (isset($_SESSION["user_id"])) : ?>
                <form method="post" action="">
                    <input type="number" name="training_id" value="<?= $training['training_id'] ?>" class="hidden">
                    <button type="submit" class="btn btn-primary reservation" name="training-btn">S'inscrire</button>
                </form>
            <?php endif ?>
        </div>
    <?php endforeach ?>
</div>