<h1>Créer une annonce</h1>

<form action="<?= url('/posts/store') ?>" method="post">
    <div class="form-group">
        <label for="post_title">Titre</label>
        <input type="text" class="form-control" name="post_title" id="post_title">
    </div>
    <div class="form-group">
        <label for="post_content">Description</label>
        <textarea name="post_content" id="post_content" cols="30" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="post_creation_date">Date d'ajout</label>
        <input type="datetime-local" class="form-control" name="post_creation_date" id="post_creation_date">
    </div>
    <div class="mt-3">
        <button class="btn btn-primary">Ajouter</button>
    </div>
</form>