<h1>Association Numérique Pour Tous</h1>

<section class="first-section">
    <p class="bienvenue">Bienvenue sur le site web de l'Association "Numérique pour tous".</p>
    <div class="firstdiv">
        <div class="texts-section">
            <p>Créée en 2020, notre association a pour but de <a class="bold">fournir des appareils numériques aux familles qui n'en ont pas, et pour former et assister les familles à leur utilisation quotidienne, tout ça gratuitement.</a><br /><br />Depuis quelques années maintenant, <a class="bold">de plus en plus d'organismes publiques et privés ont décidé de créer des interfaces numériques</a> accessibles depuis un simple ordinateur afin que tout citoyen puisse accomplir leurs démarches en toute autonomie sans avoir à se déplacer. Beaucoup d'entre ces organismes sont passés au 100% numérique et ne proposent plus d'effectuer de démarches papiers.</p>
        </div>
        <a class="first-image-home">
            <img src="/num_pour_tous/img/computer_practice.webp" alt="individu utilisant un ordinateur" class="border-radius">
        </a>
    </div>
    <div class="seconddiv">
        <div class="images">
            <a class="second-image-home">
                <img src="/num_pour_tous/img/computer_learning2.png" alt="personne agee apprenant l'utilisation d'un ordinateur" class="border-radius">
            </a>
            <a class="third-image-home">
                <img src="/num_pour_tous/img/computer_printer2.png" alt="ordinateur et imprimante sur un bureau" class="border-radius">
            </a>
        </div>
        <div class="texts-section">
            <p>L'activité de notre association consiste à récupérer des ordinateurs donnés gracieusement ainsi que des imprimantes, nous les réhabilitons si nécessaire et les donnons gratuitement aux foyers nécessiteux. <br><br><a class="bold">Nous les donnons sous forme de pack "ordinateur + imprimante". Nous proposons aussi aux familles des formations gratuites liées à leur utilisation.</a><br><br>Concrètement nous publions des annonces de packs réservables en ligne et à venir récupérer. Les foyers peuvent aussi s'inscrire à 2 formations complémentaires gratuites s'ils le souhaitent :<br><br>
            <ul class="bold">
                <li>Formation à l'utilisation d'un ordinateur, d'une imprimante et d'internet (30 minutes)</li>
                <li>Formation à l'utilisation Word (30 minutes)</li>
            </ul><br>
            <a class="bold">Ces deux prestations sont gratuites à condition que le revenu fiscal de référence du foyer soit inférieur à un certain montant, preuve à l'appui.</a>
            </p><br>
            <div>
                <p>Testez votre éligibilité en inscrivant votre revenu fiscal :</p>

                <input type="number" id="year-salary">

                <button id="valid-input">Vérifier</button>

                <div class="eligible">
                    <p class="background-green">Félicitations ! Vous êtes éligible.</p>
                </div>

                <div class="not-eligible">
                    <p class="background-red">Vos revenus sont supérieurs à la limite fixée :(</p>
                </div>

            </div>
        </div>
</section>