<!--PAGE RACINE INCLUANT HEADER-MAIN-FOOTER-->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Association "Numérique Pour Tous"</title>
    <link rel="stylesheet" href="/num_pour_tous/style.css">
    <script src="/num_pour_tous/js/main.js" type="module"></script>
</head>

<body>
    <header class="header">
        <nav class="navbar">
            <div class="logo">
                <a href="<?= url('/') ?>">
                    <img src="/num_pour_tous/img/npt_logo_2.png" alt="logo de l'association numerique pour tous" class="navbar-brand">
                </a>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<?= url('/') ?>">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="<?= url('/posts') ?>">Annonces</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="<?= url('/trainings') ?>">Formations</a>
                </li>
                <?php if (auth()->isAuthenticated()) : ?>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?= url('/logout') ?>">Déconnexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?= url('/myaccount') ?>">Mon Compte</a>
                    </li>
                <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?= url('/login') ?>">Connexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?= url('/register') ?>">Inscription</a>
                    </li>
                <?php endif ?>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container">
            <?php require $template . '.phtml' ?>
        </div>
    </main>
    <footer class="footer">
        <div class="footbar">
            <div class="logo">
                <img src="/num_pour_tous/img/npt_logo_2.png" alt="logo de l'association numerique pour tous" class="footbar-brand">
            </div>
            <div class="coordonnees">
                <p class="coordonnees-2">Association Numérique Pour Tous<br>10 avenue des Quinconces<br>33000 BORDEAUX<br>numpourtous@gmail.com<br>0612213443
                </p>
            </div>
            <div class="social-media-div">
                <a href="#" class="footbar-social-media">
                    <img src="/num_pour_tous/img/facebook-social-media-svgrepo-com.svg" alt="logo facebook" class="social-icons">
                </a>
                <a href="#" class="footbar-social-media">
                    <img src="/num_pour_tous/img/instagram-social-media-svgrepo-com.svg" alt="logo instagram" class="social-icons">
                </a>
            </div>
        </div>
    </footer>