<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Association "Numérique Pour Tous"</title>
    <link rel="stylesheet" href="/num_pour_tous/style.css"><!--""-->
</head>

<body>
    <header class="header">
        <nav class="navbar">
            <a class="navbar-brand" href="<?= url('/') ?>">
                <img src="/num_pour_tous/img/npt_logo_3.png" alt="Avatar Logo" class="logo">
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<?= url('/') ?>">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="<?= url('/posts') ?>">Annonces</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="<?= url('/trainings') ?>">Formations</a>
                </li>
                <?php if (auth()->isAuthenticated()) : ?>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?= url('/logout') ?>">Déconnexion</a>
                    </li>
                <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?= url('/login') ?>">Connexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?= url('/register') ?>">Inscription</a>
                    </li>
                <?php endif ?>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container">
            <?php require $template . '.phtml' ?>
        </div>
    </main>
    <footer class="footer">
        <div class="footbar">
            <a class="footbar-brand">
                <img src="/num_pour_tous/img/npt_logo_3.png" alt="Avatar Logo" class="logo">
            </a>
            <div class="coordonnees">
                <p class="coordonnees-2">Association Numérique Pour Tous<br>10 avenue des Quinconces<br>33000 BORDEAUX<br>numpourtous@gmail.com<br>0612213443
                </p>
            </div>
            <div class="social-media-div">
                <a href="#" class="footbar-social-media">
                    <img src="/num_pour_tous/img/facebook-social-media-svgrepo-com.svg" alt="" class="social-icons">
                </a>
                <a href="#" class="footbar-social-media">
                    <img src="/num_pour_tous/img/instagram-social-media-svgrepo-com.svg" alt="" class="social-icons">
                </a>
            </div>
        </div>
    </footer>